---
- name: Fetch Results
  hosts: "{{ molecule_robotframework_hosts | d('all') }}"
  vars:
    dest_dir:    "{{ molecule_yml.verifier.dest_dir | d(molecule_scenario_directory+'/output') }}"
    outputdir:   "{{ molecule_yml.verifier.options.outputdir | d('.') }}"
    output_file: "{{ molecule_yml.verifier.options.output | d('output.xml') }}"
    log_file:    "{{ molecule_yml.verifier.options.log | d('log.html') }}"
    report_file: "{{ molecule_yml.verifier.options.report | d('report.html') }}"
    debug_file:  "{{ molecule_yml.verifier.options.debugfile | d('debug.log') }}"
  tasks:
    - name: Ensure debug file is present.
      copy:
        content: "Add the robot 'debugfile' option to enable debug logging."
        dest: "{{ debug_file }}"
        force: no

    - name: Download test reports and logs.
      fetch:
        flat: "{{ (ansible_play_hosts | count == 1) | ternary('yes', 'no') }}"
        src: "{{ item }}"
        dest: "{{ dest_dir }}/"
      with_items:
        - "{{ outputdir }}/{{ output_file }}"
        - "{{ outputdir }}/{{ log_file }}"
        - "{{ outputdir }}/{{ report_file }}"
        - "{{ debug_file }}"
      register: fetch_results

    - name: Downloaded test reports and logs
      debug:
        msg: "{{ fetch_results.results | map(attribute='dest') }}"
